import { BagIcon, PlusIcon, SearchIcon } from "../_components/icons";
import { PageHeader } from "../_components/page-header";

const products = [
  { name: "Amber mist", price: "¥2,200", stock: "残り 8", tone: "bg-[#f5c2e7]" },
  { name: "Sunday garden", price: "¥2,400", stock: "残り 3", tone: "bg-[#bceee9]" },
  { name: "Morning sachet", price: "¥800", stock: "残り 12", tone: "bg-[#fff0b3]" },
  { name: "Petal candle", price: "¥1,600", stock: "残り 1", tone: "bg-[#d8d3ff]" },
];

export default function SellPage() {
  return <>
    <PageHeader eyebrow="SELL" title="売る" />
    <div className="mb-7 flex w-full gap-1 overflow-x-auto rounded-full bg-[#ececf1] p-1 sm:w-fit"><button className="h-9 shrink-0 rounded-full bg-[#050038] px-5 text-sm font-medium text-white">販売</button><button className="h-9 shrink-0 rounded-full px-5 text-sm font-medium text-[#52526a]">在庫</button><button className="h-9 shrink-0 rounded-full px-5 text-sm font-medium text-[#52526a]">委託</button></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-medium tracking-[-0.04em]">Summer Market</h2><p className="mt-1 text-sm text-[#77778d]">イベント会場の在庫から販売します。</p></div><button className="inline-flex h-10 items-center gap-2 rounded-full border border-[#b9b9ca] bg-white px-4 text-sm font-medium"><PlusIcon className="h-4 w-4"/>商品を追加</button></div><div className="mb-4 flex h-11 items-center gap-2 rounded-lg border border-[#c7c7de] bg-white px-3"><SearchIcon className="h-5 w-5 text-[#77778d]"/><span className="text-sm text-[#77778d]">商品名で検索</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{products.map((product) => <button key={product.name} className="rounded-[22px] border border-[#dedee8] bg-white p-3 text-left transition active:scale-[0.98] sm:p-4"><span className={`block aspect-square rounded-[16px] ${product.tone}`}><span className="grid h-full place-items-center"><BagIcon className="h-7 w-7"/></span></span><p className="mt-3 truncate text-sm font-medium">{product.name}</p><div className="mt-1 flex items-end justify-between gap-1"><span className="text-sm font-medium">{product.price}</span><span className={`text-[11px] ${product.stock === "残り 1" ? "font-semibold text-[#d12929]" : "text-[#77778d]"}`}>{product.stock}</span></div></button>)}</div></section><aside className="self-start rounded-[28px] bg-[#050038] p-5 text-white shadow-[0_12px_32px_-4px_rgba(5,0,56,0.2)] sm:p-6 xl:sticky xl:top-7"><div className="flex items-center justify-between"><h2 className="text-lg font-medium">カート</h2><span className="rounded-full bg-white/15 px-2.5 py-1 text-xs">2 点</span></div><div className="mt-6 space-y-4 border-y border-white/15 py-5"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">Amber mist <span className="ml-1 text-xs text-white/60">× 1</span></p><p className="mt-1 text-xs text-white/60">¥2,200</p></div><button className="text-xs text-white/60 underline underline-offset-4">削除</button></div><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">Morning sachet <span className="ml-1 text-xs text-white/60">× 2</span></p><p className="mt-1 text-xs text-white/60">¥800 × 2</p></div><button className="text-xs text-white/60 underline underline-offset-4">削除</button></div></div><div className="mt-5 flex items-end justify-between"><span className="text-sm text-white/65">合計</span><span className="text-4xl font-medium tracking-[-0.06em]">¥3,800</span></div><button className="mt-6 flex h-12 w-full items-center justify-center rounded-full bg-[#ffd02f] text-sm font-semibold text-[#050038]">会計へ進む</button><p className="mt-3 text-center text-xs text-white/55">会計時に顧客情報を記録できます</p></aside></div>
  </>;
}
