import Link from "next/link";
import { ArrowIcon, ClockIcon, MoreIcon, PlusIcon, SearchIcon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";

const recipes = [
  { name: "Jasmine pillar", detail: "ソイ 70% · 蜜蝋 30% · CD-10", tag: "PILLAR", tone: "bg-[#f5c2e7]" },
  { name: "Amber mist", detail: "ソイ 100% · 木芯 S", tag: "TIN", tone: "bg-[#bceee9]" },
  { name: "Sunday garden", detail: "パラフィン 80% · ソイ 20% · CD-8", tag: "GLASS", tone: "bg-[#fff0b3]" },
];

export default function CreatePage() {
  return <>
    <PageHeader eyebrow="MAKE" title="つくる" action={<Link href="/create" className="hidden h-10 items-center gap-2 rounded-full bg-[#050038] px-4 text-sm font-medium text-white sm:inline-flex"><PlusIcon className="h-4 w-4"/>新しい実験</Link>} />
    <div className="mb-7 flex w-fit gap-1 overflow-x-auto rounded-full bg-[#ececf1] p-1"><button className="h-9 shrink-0 rounded-full bg-[#050038] px-5 text-sm font-medium text-white">実験</button><button className="h-9 shrink-0 rounded-full px-5 text-sm font-medium text-[#52526a]">レシピ</button></div>
    <section className="mb-9"><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-medium tracking-[-0.04em]">進行中の実験</h2><p className="mt-1 text-sm text-[#77778d]">記録のタイミングを逃さず、結果を残します。</p></div><span className="hidden text-xs text-[#77778d] sm:block">1件 進行中</span></div><div className="overflow-hidden rounded-[28px] border border-[#c7c7de] bg-white"><div className="grid lg:grid-cols-[1.1fr_1fr]"><div className="bg-[#f5c2e7] p-6 sm:p-8"><span className="inline-flex items-center gap-1.5 rounded-full bg-white/85 px-3 py-1 text-xs font-semibold"><span className="h-1.5 w-1.5 rounded-full bg-[#13a36b]"/>進行中</span><h3 className="mt-7 text-3xl font-medium tracking-[-0.06em]">Jasmine pillar<br/>Test 03</h3><p className="mt-3 text-sm leading-6 text-[#52526a]">ジャスミンの香り立ちと、燃焼プールの広がりを観察中です。</p><div className="mt-7 flex flex-wrap gap-2"><button className="inline-flex h-11 items-center gap-2 rounded-full bg-[#050038] px-5 text-sm font-medium text-white"><PlusIcon className="h-4 w-4"/>観察を記録</button><button aria-label="その他の操作" className="grid h-11 w-11 place-items-center rounded-full border border-[#a9a9bd] bg-white"><MoreIcon className="h-5 w-5"/></button></div></div><div className="p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-semibold text-[#77778d]"><ClockIcon className="h-4 w-4"/>ELAPSED TIME</div><p className="mt-3 text-5xl font-medium tracking-[-0.07em]">02:34:18</p><div className="mt-7 space-y-3"><div className="flex items-start gap-3 border-l-2 border-[#050038] pl-3"><span className="mt-0.5 text-xs text-[#77778d]">10:24</span><p className="text-sm">炎は安定。プール径 52mm を記録。</p></div><div className="flex items-start gap-3 border-l-2 border-[#dedee8] pl-3"><span className="mt-0.5 text-xs text-[#77778d]">09:32</span><p className="text-sm text-[#77778d]">実験を開始しました。</p></div></div></div></div></div></section>
    <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-medium tracking-[-0.04em]">よく使うレシピ</h2><p className="mt-1 text-sm text-[#77778d]">レシピを選ぶと、すぐに実験を開始できます。</p></div><Link href="/settings" className="hidden items-center gap-1 text-sm font-medium text-[#4262ff] sm:inline-flex">すべて見る <ArrowIcon className="h-4 w-4"/></Link></div><div className="mb-4 flex h-11 max-w-md items-center gap-2 rounded-lg border border-[#c7c7de] bg-white px-3"><SearchIcon className="h-5 w-5 text-[#77778d]"/><span className="text-sm text-[#77778d]">レシピを検索</span></div><div className="grid gap-3 md:grid-cols-3">{recipes.map((recipe) => <article key={recipe.name} className="group rounded-[24px] border border-[#dedee8] bg-white p-5"><span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${recipe.tone}`}>{recipe.tag}</span><h3 className="mt-8 text-lg font-medium tracking-[-0.04em]">{recipe.name}</h3><p className="mt-2 text-sm leading-6 text-[#77778d]">{recipe.detail}</p><Link href="/create" className="mt-6 inline-flex h-10 items-center gap-1 rounded-full border border-[#b9b9ca] px-4 text-sm font-medium">このレシピで始める <ArrowIcon className="h-4 w-4"/></Link></article>)}</div></section>
  </>;
}
